version: '3.7'

services:
  client:
    container_name: client
    command: serve -s build
    image: client
    build: 
      context: client/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  server:
    container_name: server
    command: npm run start:prod
    image: server
    build: 
      context: server/
      dockerfile: Dockerfile
    ports:
      - 80:80